# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# source
source 'https://github.com/CocoaPods/Specs.git'

target 'favqstest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for favqstest
  # UI
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 6.0'
  # Networking
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '<= 5.2'
  # Utils
  ## SwiftGen is use to generate swift extension from .xcassets
  ## Added script in 'Script Build Phase'
  pod 'SwiftGen', '~> 6.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'

    end
  end

  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end